// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vcassist/services/gradesnapshots/v1/api.proto

package gradesnapshotsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "vcassist-backend/proto/vcassist/services/gradesnapshots/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GradeSnapshotsServiceName is the fully-qualified name of the GradeSnapshotsService service.
	GradeSnapshotsServiceName = "vcassist.services.gradesnapshots.v1.GradeSnapshotsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GradeSnapshotsServicePushProcedure is the fully-qualified name of the GradeSnapshotsService's
	// Push RPC.
	GradeSnapshotsServicePushProcedure = "/vcassist.services.gradesnapshots.v1.GradeSnapshotsService/Push"
	// GradeSnapshotsServicePullProcedure is the fully-qualified name of the GradeSnapshotsService's
	// Pull RPC.
	GradeSnapshotsServicePullProcedure = "/vcassist.services.gradesnapshots.v1.GradeSnapshotsService/Pull"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	gradeSnapshotsServiceServiceDescriptor    = v1.File_vcassist_services_gradesnapshots_v1_api_proto.Services().ByName("GradeSnapshotsService")
	gradeSnapshotsServicePushMethodDescriptor = gradeSnapshotsServiceServiceDescriptor.Methods().ByName("Push")
	gradeSnapshotsServicePullMethodDescriptor = gradeSnapshotsServiceServiceDescriptor.Methods().ByName("Pull")
)

// GradeSnapshotsServiceClient is a client for the
// vcassist.services.gradesnapshots.v1.GradeSnapshotsService service.
type GradeSnapshotsServiceClient interface {
	Push(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error)
	Pull(context.Context, *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error)
}

// NewGradeSnapshotsServiceClient constructs a client for the
// vcassist.services.gradesnapshots.v1.GradeSnapshotsService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGradeSnapshotsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GradeSnapshotsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &gradeSnapshotsServiceClient{
		push: connect.NewClient[v1.PushRequest, v1.PushResponse](
			httpClient,
			baseURL+GradeSnapshotsServicePushProcedure,
			connect.WithSchema(gradeSnapshotsServicePushMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		pull: connect.NewClient[v1.PullRequest, v1.PullResponse](
			httpClient,
			baseURL+GradeSnapshotsServicePullProcedure,
			connect.WithSchema(gradeSnapshotsServicePullMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// gradeSnapshotsServiceClient implements GradeSnapshotsServiceClient.
type gradeSnapshotsServiceClient struct {
	push *connect.Client[v1.PushRequest, v1.PushResponse]
	pull *connect.Client[v1.PullRequest, v1.PullResponse]
}

// Push calls vcassist.services.gradesnapshots.v1.GradeSnapshotsService.Push.
func (c *gradeSnapshotsServiceClient) Push(ctx context.Context, req *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error) {
	return c.push.CallUnary(ctx, req)
}

// Pull calls vcassist.services.gradesnapshots.v1.GradeSnapshotsService.Pull.
func (c *gradeSnapshotsServiceClient) Pull(ctx context.Context, req *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error) {
	return c.pull.CallUnary(ctx, req)
}

// GradeSnapshotsServiceHandler is an implementation of the
// vcassist.services.gradesnapshots.v1.GradeSnapshotsService service.
type GradeSnapshotsServiceHandler interface {
	Push(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error)
	Pull(context.Context, *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error)
}

// NewGradeSnapshotsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGradeSnapshotsServiceHandler(svc GradeSnapshotsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gradeSnapshotsServicePushHandler := connect.NewUnaryHandler(
		GradeSnapshotsServicePushProcedure,
		svc.Push,
		connect.WithSchema(gradeSnapshotsServicePushMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	gradeSnapshotsServicePullHandler := connect.NewUnaryHandler(
		GradeSnapshotsServicePullProcedure,
		svc.Pull,
		connect.WithSchema(gradeSnapshotsServicePullMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vcassist.services.gradesnapshots.v1.GradeSnapshotsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GradeSnapshotsServicePushProcedure:
			gradeSnapshotsServicePushHandler.ServeHTTP(w, r)
		case GradeSnapshotsServicePullProcedure:
			gradeSnapshotsServicePullHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGradeSnapshotsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGradeSnapshotsServiceHandler struct{}

func (UnimplementedGradeSnapshotsServiceHandler) Push(context.Context, *connect.Request[v1.PushRequest]) (*connect.Response[v1.PushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.gradesnapshots.v1.GradeSnapshotsService.Push is not implemented"))
}

func (UnimplementedGradeSnapshotsServiceHandler) Pull(context.Context, *connect.Request[v1.PullRequest]) (*connect.Response[v1.PullResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.gradesnapshots.v1.GradeSnapshotsService.Pull is not implemented"))
}
