// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file vcassist/services/keychain/v1/api.proto (package vcassist.services.keychain.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOAuthRequest, GetOAuthResponse, GetUsernamePasswordRequest, GetUsernamePasswordResponse, SetOAuthRequest, SetOAuthResponse, SetUsernamePasswordRequest, SetUsernamePasswordResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service vcassist.services.keychain.v1.KeychainService
 */
export const KeychainService = {
  typeName: "vcassist.services.keychain.v1.KeychainService",
  methods: {
    /**
     * @generated from rpc vcassist.services.keychain.v1.KeychainService.SetOAuth
     */
    setOAuth: {
      name: "SetOAuth",
      I: SetOAuthRequest,
      O: SetOAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.keychain.v1.KeychainService.GetOAuth
     */
    getOAuth: {
      name: "GetOAuth",
      I: GetOAuthRequest,
      O: GetOAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.keychain.v1.KeychainService.SetUsernamePassword
     */
    setUsernamePassword: {
      name: "SetUsernamePassword",
      I: SetUsernamePasswordRequest,
      O: SetUsernamePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.keychain.v1.KeychainService.GetUsernamePassword
     */
    getUsernamePassword: {
      name: "GetUsernamePassword",
      I: GetUsernamePasswordRequest,
      O: GetUsernamePasswordResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

