// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/studentdata/api/api.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	api "vcassist-backend/services/studentdata/api"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StudentDataServiceName is the fully-qualified name of the StudentDataService service.
	StudentDataServiceName = "services.studentdata.api.StudentDataService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StudentDataServiceGetCredentialStatusProcedure is the fully-qualified name of the
	// StudentDataService's GetCredentialStatus RPC.
	StudentDataServiceGetCredentialStatusProcedure = "/services.studentdata.api.StudentDataService/GetCredentialStatus"
	// StudentDataServiceProvideCredentialProcedure is the fully-qualified name of the
	// StudentDataService's ProvideCredential RPC.
	StudentDataServiceProvideCredentialProcedure = "/services.studentdata.api.StudentDataService/ProvideCredential"
	// StudentDataServiceGetStudentDataProcedure is the fully-qualified name of the StudentDataService's
	// GetStudentData RPC.
	StudentDataServiceGetStudentDataProcedure = "/services.studentdata.api.StudentDataService/GetStudentData"
	// StudentDataServiceRefreshDataProcedure is the fully-qualified name of the StudentDataService's
	// RefreshData RPC.
	StudentDataServiceRefreshDataProcedure = "/services.studentdata.api.StudentDataService/RefreshData"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	studentDataServiceServiceDescriptor                   = api.File_services_studentdata_api_api_proto.Services().ByName("StudentDataService")
	studentDataServiceGetCredentialStatusMethodDescriptor = studentDataServiceServiceDescriptor.Methods().ByName("GetCredentialStatus")
	studentDataServiceProvideCredentialMethodDescriptor   = studentDataServiceServiceDescriptor.Methods().ByName("ProvideCredential")
	studentDataServiceGetStudentDataMethodDescriptor      = studentDataServiceServiceDescriptor.Methods().ByName("GetStudentData")
	studentDataServiceRefreshDataMethodDescriptor         = studentDataServiceServiceDescriptor.Methods().ByName("RefreshData")
)

// StudentDataServiceClient is a client for the services.studentdata.api.StudentDataService service.
type StudentDataServiceClient interface {
	GetCredentialStatus(context.Context, *connect.Request[api.GetCredentialStatusRequest]) (*connect.Response[api.GetCredentialStatusResponse], error)
	ProvideCredential(context.Context, *connect.Request[api.ProvideCredentialRequest]) (*connect.Response[api.ProvideCredentialResponse], error)
	GetStudentData(context.Context, *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error)
	RefreshData(context.Context, *connect.Request[api.RefreshDataRequest]) (*connect.Response[api.RefreshDataResponse], error)
}

// NewStudentDataServiceClient constructs a client for the
// services.studentdata.api.StudentDataService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStudentDataServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StudentDataServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &studentDataServiceClient{
		getCredentialStatus: connect.NewClient[api.GetCredentialStatusRequest, api.GetCredentialStatusResponse](
			httpClient,
			baseURL+StudentDataServiceGetCredentialStatusProcedure,
			connect.WithSchema(studentDataServiceGetCredentialStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		provideCredential: connect.NewClient[api.ProvideCredentialRequest, api.ProvideCredentialResponse](
			httpClient,
			baseURL+StudentDataServiceProvideCredentialProcedure,
			connect.WithSchema(studentDataServiceProvideCredentialMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getStudentData: connect.NewClient[api.GetStudentDataRequest, api.GetStudentDataResponse](
			httpClient,
			baseURL+StudentDataServiceGetStudentDataProcedure,
			connect.WithSchema(studentDataServiceGetStudentDataMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		refreshData: connect.NewClient[api.RefreshDataRequest, api.RefreshDataResponse](
			httpClient,
			baseURL+StudentDataServiceRefreshDataProcedure,
			connect.WithSchema(studentDataServiceRefreshDataMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// studentDataServiceClient implements StudentDataServiceClient.
type studentDataServiceClient struct {
	getCredentialStatus *connect.Client[api.GetCredentialStatusRequest, api.GetCredentialStatusResponse]
	provideCredential   *connect.Client[api.ProvideCredentialRequest, api.ProvideCredentialResponse]
	getStudentData      *connect.Client[api.GetStudentDataRequest, api.GetStudentDataResponse]
	refreshData         *connect.Client[api.RefreshDataRequest, api.RefreshDataResponse]
}

// GetCredentialStatus calls services.studentdata.api.StudentDataService.GetCredentialStatus.
func (c *studentDataServiceClient) GetCredentialStatus(ctx context.Context, req *connect.Request[api.GetCredentialStatusRequest]) (*connect.Response[api.GetCredentialStatusResponse], error) {
	return c.getCredentialStatus.CallUnary(ctx, req)
}

// ProvideCredential calls services.studentdata.api.StudentDataService.ProvideCredential.
func (c *studentDataServiceClient) ProvideCredential(ctx context.Context, req *connect.Request[api.ProvideCredentialRequest]) (*connect.Response[api.ProvideCredentialResponse], error) {
	return c.provideCredential.CallUnary(ctx, req)
}

// GetStudentData calls services.studentdata.api.StudentDataService.GetStudentData.
func (c *studentDataServiceClient) GetStudentData(ctx context.Context, req *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error) {
	return c.getStudentData.CallUnary(ctx, req)
}

// RefreshData calls services.studentdata.api.StudentDataService.RefreshData.
func (c *studentDataServiceClient) RefreshData(ctx context.Context, req *connect.Request[api.RefreshDataRequest]) (*connect.Response[api.RefreshDataResponse], error) {
	return c.refreshData.CallUnary(ctx, req)
}

// StudentDataServiceHandler is an implementation of the services.studentdata.api.StudentDataService
// service.
type StudentDataServiceHandler interface {
	GetCredentialStatus(context.Context, *connect.Request[api.GetCredentialStatusRequest]) (*connect.Response[api.GetCredentialStatusResponse], error)
	ProvideCredential(context.Context, *connect.Request[api.ProvideCredentialRequest]) (*connect.Response[api.ProvideCredentialResponse], error)
	GetStudentData(context.Context, *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error)
	RefreshData(context.Context, *connect.Request[api.RefreshDataRequest]) (*connect.Response[api.RefreshDataResponse], error)
}

// NewStudentDataServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStudentDataServiceHandler(svc StudentDataServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	studentDataServiceGetCredentialStatusHandler := connect.NewUnaryHandler(
		StudentDataServiceGetCredentialStatusProcedure,
		svc.GetCredentialStatus,
		connect.WithSchema(studentDataServiceGetCredentialStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	studentDataServiceProvideCredentialHandler := connect.NewUnaryHandler(
		StudentDataServiceProvideCredentialProcedure,
		svc.ProvideCredential,
		connect.WithSchema(studentDataServiceProvideCredentialMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	studentDataServiceGetStudentDataHandler := connect.NewUnaryHandler(
		StudentDataServiceGetStudentDataProcedure,
		svc.GetStudentData,
		connect.WithSchema(studentDataServiceGetStudentDataMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	studentDataServiceRefreshDataHandler := connect.NewUnaryHandler(
		StudentDataServiceRefreshDataProcedure,
		svc.RefreshData,
		connect.WithSchema(studentDataServiceRefreshDataMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/services.studentdata.api.StudentDataService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StudentDataServiceGetCredentialStatusProcedure:
			studentDataServiceGetCredentialStatusHandler.ServeHTTP(w, r)
		case StudentDataServiceProvideCredentialProcedure:
			studentDataServiceProvideCredentialHandler.ServeHTTP(w, r)
		case StudentDataServiceGetStudentDataProcedure:
			studentDataServiceGetStudentDataHandler.ServeHTTP(w, r)
		case StudentDataServiceRefreshDataProcedure:
			studentDataServiceRefreshDataHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStudentDataServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStudentDataServiceHandler struct{}

func (UnimplementedStudentDataServiceHandler) GetCredentialStatus(context.Context, *connect.Request[api.GetCredentialStatusRequest]) (*connect.Response[api.GetCredentialStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.studentdata.api.StudentDataService.GetCredentialStatus is not implemented"))
}

func (UnimplementedStudentDataServiceHandler) ProvideCredential(context.Context, *connect.Request[api.ProvideCredentialRequest]) (*connect.Response[api.ProvideCredentialResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.studentdata.api.StudentDataService.ProvideCredential is not implemented"))
}

func (UnimplementedStudentDataServiceHandler) GetStudentData(context.Context, *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.studentdata.api.StudentDataService.GetStudentData is not implemented"))
}

func (UnimplementedStudentDataServiceHandler) RefreshData(context.Context, *connect.Request[api.RefreshDataRequest]) (*connect.Response[api.RefreshDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.studentdata.api.StudentDataService.RefreshData is not implemented"))
}
