// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: vcassist/services/vcmoodle/v1/api.proto

package vcmoodlev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCourses
type ResourceType int32

const (
	ResourceType_GENERIC_URL ResourceType = 0
	ResourceType_FILE        ResourceType = 1
	ResourceType_BOOK        ResourceType = 2
	ResourceType_HTML_AREA   ResourceType = 3
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "GENERIC_URL",
		1: "FILE",
		2: "BOOK",
		3: "HTML_AREA",
	}
	ResourceType_value = map[string]int32{
		"GENERIC_URL": 0,
		"FILE":        1,
		"BOOK":        2,
		"HTML_AREA":   3,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_vcassist_services_vcmoodle_v1_api_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_vcassist_services_vcmoodle_v1_api_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{0}
}

// GetAuthStatus
type GetAuthStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAuthStatusRequest) Reset() {
	*x = GetAuthStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStatusRequest) ProtoMessage() {}

func (x *GetAuthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAuthStatusRequest) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{0}
}

type GetAuthStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provided bool `protobuf:"varint,1,opt,name=provided,proto3" json:"provided,omitempty"`
}

func (x *GetAuthStatusResponse) Reset() {
	*x = GetAuthStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStatusResponse) ProtoMessage() {}

func (x *GetAuthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAuthStatusResponse) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthStatusResponse) GetProvided() bool {
	if x != nil {
		return x.Provided
	}
	return false
}

// ProvideUsernamePassword
type ProvideUsernamePasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ProvideUsernamePasswordRequest) Reset() {
	*x = ProvideUsernamePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvideUsernamePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideUsernamePasswordRequest) ProtoMessage() {}

func (x *ProvideUsernamePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideUsernamePasswordRequest.ProtoReflect.Descriptor instead.
func (*ProvideUsernamePasswordRequest) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *ProvideUsernamePasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProvideUsernamePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ProvideUsernamePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProvideUsernamePasswordResponse) Reset() {
	*x = ProvideUsernamePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvideUsernamePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideUsernamePasswordResponse) ProtoMessage() {}

func (x *ProvideUsernamePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideUsernamePasswordResponse.ProtoReflect.Descriptor instead.
func (*ProvideUsernamePasswordResponse) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{3}
}

type Chapter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// if this field is not null, the html in this field will be displayed
	// on the home page as "today's lesson plan" for the course it belongs to
	HomepageContent string `protobuf:"bytes,4,opt,name=homepage_content,json=homepageContent,proto3" json:"homepage_content,omitempty"`
	// the dates the chapter likely belongs to
	Dates []int64 `protobuf:"varint,5,rep,packed,name=dates,proto3" json:"dates,omitempty"`
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *Chapter) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chapter) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Chapter) GetHomepageContent() string {
	if x != nil {
		return x.HomepageContent
	}
	return ""
}

func (x *Chapter) GetDates() []int64 {
	if x != nil {
		return x.Dates
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx            int64        `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Type           ResourceType `protobuf:"varint,2,opt,name=type,proto3,enum=vcassist.services.vcmoodle.v1.ResourceType" json:"type,omitempty"`
	Url            string       `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	DisplayContent string       `protobuf:"bytes,4,opt,name=display_content,json=displayContent,proto3" json:"display_content,omitempty"`
	// this will be null for resources that are not BOOK
	Chapters []*Chapter `protobuf:"bytes,5,rep,name=chapters,proto3" json:"chapters,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *Resource) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_GENERIC_URL
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetDisplayContent() string {
	if x != nil {
		return x.DisplayContent
	}
	return ""
}

func (x *Resource) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type Section struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx       int64       `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Name      string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url       string      `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Resources []*Resource `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *Section) Reset() {
	*x = Section{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *Section) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Section) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Section) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Course struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Teacher  string     `protobuf:"bytes,3,opt,name=teacher,proto3" json:"teacher,omitempty"`
	Url      string     `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Sections []*Section `protobuf:"bytes,5,rep,name=sections,proto3" json:"sections,omitempty"`
}

func (x *Course) Reset() {
	*x = Course{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *Course) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *Course) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Course) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

type GetCoursesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{8}
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courses []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

// GetChapterContent
type GetChapterContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetChapterContentRequest) Reset() {
	*x = GetChapterContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChapterContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterContentRequest) ProtoMessage() {}

func (x *GetChapterContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterContentRequest.ProtoReflect.Descriptor instead.
func (*GetChapterContentRequest) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetChapterContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetChapterContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Html string `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
}

func (x *GetChapterContentResponse) Reset() {
	*x = GetChapterContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChapterContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterContentResponse) ProtoMessage() {}

func (x *GetChapterContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterContentResponse.ProtoReflect.Descriptor instead.
func (*GetChapterContentResponse) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetChapterContentResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

// GetFileContent
type GetFileContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFileContentRequest) Reset() {
	*x = GetFileContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentRequest) ProtoMessage() {}

func (x *GetFileContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentRequest.ProtoReflect.Descriptor instead.
func (*GetFileContentRequest) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFileContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Last  bool   `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *GetFileContentResponse) Reset() {
	*x = GetFileContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentResponse) ProtoMessage() {}

func (x *GetFileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentResponse.ProtoReflect.Descriptor instead.
func (*GetFileContentResponse) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileContentResponse) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *GetFileContentResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// RefreshCourses
type RefreshCoursesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshCoursesRequest) Reset() {
	*x = RefreshCoursesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCoursesRequest) ProtoMessage() {}

func (x *RefreshCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCoursesRequest.ProtoReflect.Descriptor instead.
func (*RefreshCoursesRequest) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{14}
}

type RefreshCoursesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courses []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
}

func (x *RefreshCoursesResponse) Reset() {
	*x = RefreshCoursesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCoursesResponse) ProtoMessage() {}

func (x *RefreshCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCoursesResponse.ProtoReflect.Descriptor instead.
func (*RefreshCoursesResponse) Descriptor() ([]byte, []int) {
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

var File_vcassist_services_vcmoodle_v1_api_proto protoreflect.FileDescriptor

var file_vcassist_services_vcmoodle_v1_api_proto_rawDesc = []byte{
	0x0a, 0x27, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x76, 0x63, 0x61, 0x73, 0x73,
	0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d,
	0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x33, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x64, 0x22, 0x58, 0x0a, 0x1e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x21, 0x0a, 0x1f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x29, 0x0a, 0x10, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0xdc, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x69, 0x64, 0x78, 0x12, 0x3f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x42, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x08, 0x63, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69,
	0x64, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x45, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x63,
	0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22,
	0x9c, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x42, 0x0a, 0x08, 0x73, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76,
	0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x13,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x76, 0x63, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x42, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a,
	0x16, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73,
	0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d,
	0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x2a, 0x42, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x45, 0x4e, 0x45,
	0x52, 0x49, 0x43, 0x5f, 0x55, 0x52, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c,
	0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x48, 0x54, 0x4d, 0x4c, 0x5f, 0x41, 0x52, 0x45, 0x41, 0x10, 0x03, 0x32, 0xa2, 0x06, 0x0a,
	0x0d, 0x4d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7a,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x33, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x98, 0x01, 0x0a, 0x17, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x3d, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f,
	0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x73, 0x12, 0x30, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7d, 0x0a, 0x0e, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x34, 0x2e, 0x76, 0x63, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x35, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x2e,
	0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73,
	0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f,
	0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x7f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x34, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73,
	0x69, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d,
	0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x85, 0x02, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x63, 0x6d, 0x6f,
	0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x08, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x76, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x2d, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x63, 0x61, 0x73,
	0x73, 0x69, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x63,
	0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x63, 0x6d, 0x6f, 0x6f, 0x64,
	0x6c, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56, 0x53, 0x56, 0xaa, 0x02, 0x1d, 0x56, 0x63, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x56,
	0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x1d, 0x56, 0x63, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x5c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5c, 0x56,
	0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x29, 0x56, 0x63, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x74, 0x5c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5c, 0x56,
	0x63, 0x6d, 0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x20, 0x56, 0x63, 0x61, 0x73, 0x73, 0x69, 0x73,
	0x74, 0x3a, 0x3a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x3a, 0x3a, 0x56, 0x63, 0x6d,
	0x6f, 0x6f, 0x64, 0x6c, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vcassist_services_vcmoodle_v1_api_proto_rawDescOnce sync.Once
	file_vcassist_services_vcmoodle_v1_api_proto_rawDescData = file_vcassist_services_vcmoodle_v1_api_proto_rawDesc
)

func file_vcassist_services_vcmoodle_v1_api_proto_rawDescGZIP() []byte {
	file_vcassist_services_vcmoodle_v1_api_proto_rawDescOnce.Do(func() {
		file_vcassist_services_vcmoodle_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_vcassist_services_vcmoodle_v1_api_proto_rawDescData)
	})
	return file_vcassist_services_vcmoodle_v1_api_proto_rawDescData
}

var file_vcassist_services_vcmoodle_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vcassist_services_vcmoodle_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_vcassist_services_vcmoodle_v1_api_proto_goTypes = []any{
	(ResourceType)(0),                       // 0: vcassist.services.vcmoodle.v1.ResourceType
	(*GetAuthStatusRequest)(nil),            // 1: vcassist.services.vcmoodle.v1.GetAuthStatusRequest
	(*GetAuthStatusResponse)(nil),           // 2: vcassist.services.vcmoodle.v1.GetAuthStatusResponse
	(*ProvideUsernamePasswordRequest)(nil),  // 3: vcassist.services.vcmoodle.v1.ProvideUsernamePasswordRequest
	(*ProvideUsernamePasswordResponse)(nil), // 4: vcassist.services.vcmoodle.v1.ProvideUsernamePasswordResponse
	(*Chapter)(nil),                         // 5: vcassist.services.vcmoodle.v1.Chapter
	(*Resource)(nil),                        // 6: vcassist.services.vcmoodle.v1.Resource
	(*Section)(nil),                         // 7: vcassist.services.vcmoodle.v1.Section
	(*Course)(nil),                          // 8: vcassist.services.vcmoodle.v1.Course
	(*GetCoursesRequest)(nil),               // 9: vcassist.services.vcmoodle.v1.GetCoursesRequest
	(*GetCoursesResponse)(nil),              // 10: vcassist.services.vcmoodle.v1.GetCoursesResponse
	(*GetChapterContentRequest)(nil),        // 11: vcassist.services.vcmoodle.v1.GetChapterContentRequest
	(*GetChapterContentResponse)(nil),       // 12: vcassist.services.vcmoodle.v1.GetChapterContentResponse
	(*GetFileContentRequest)(nil),           // 13: vcassist.services.vcmoodle.v1.GetFileContentRequest
	(*GetFileContentResponse)(nil),          // 14: vcassist.services.vcmoodle.v1.GetFileContentResponse
	(*RefreshCoursesRequest)(nil),           // 15: vcassist.services.vcmoodle.v1.RefreshCoursesRequest
	(*RefreshCoursesResponse)(nil),          // 16: vcassist.services.vcmoodle.v1.RefreshCoursesResponse
}
var file_vcassist_services_vcmoodle_v1_api_proto_depIdxs = []int32{
	0,  // 0: vcassist.services.vcmoodle.v1.Resource.type:type_name -> vcassist.services.vcmoodle.v1.ResourceType
	5,  // 1: vcassist.services.vcmoodle.v1.Resource.chapters:type_name -> vcassist.services.vcmoodle.v1.Chapter
	6,  // 2: vcassist.services.vcmoodle.v1.Section.resources:type_name -> vcassist.services.vcmoodle.v1.Resource
	7,  // 3: vcassist.services.vcmoodle.v1.Course.sections:type_name -> vcassist.services.vcmoodle.v1.Section
	8,  // 4: vcassist.services.vcmoodle.v1.GetCoursesResponse.courses:type_name -> vcassist.services.vcmoodle.v1.Course
	8,  // 5: vcassist.services.vcmoodle.v1.RefreshCoursesResponse.courses:type_name -> vcassist.services.vcmoodle.v1.Course
	1,  // 6: vcassist.services.vcmoodle.v1.MoodleService.GetAuthStatus:input_type -> vcassist.services.vcmoodle.v1.GetAuthStatusRequest
	3,  // 7: vcassist.services.vcmoodle.v1.MoodleService.ProvideUsernamePassword:input_type -> vcassist.services.vcmoodle.v1.ProvideUsernamePasswordRequest
	9,  // 8: vcassist.services.vcmoodle.v1.MoodleService.GetCourses:input_type -> vcassist.services.vcmoodle.v1.GetCoursesRequest
	15, // 9: vcassist.services.vcmoodle.v1.MoodleService.RefreshCourses:input_type -> vcassist.services.vcmoodle.v1.RefreshCoursesRequest
	11, // 10: vcassist.services.vcmoodle.v1.MoodleService.GetChapterContent:input_type -> vcassist.services.vcmoodle.v1.GetChapterContentRequest
	13, // 11: vcassist.services.vcmoodle.v1.MoodleService.GetFileContent:input_type -> vcassist.services.vcmoodle.v1.GetFileContentRequest
	2,  // 12: vcassist.services.vcmoodle.v1.MoodleService.GetAuthStatus:output_type -> vcassist.services.vcmoodle.v1.GetAuthStatusResponse
	4,  // 13: vcassist.services.vcmoodle.v1.MoodleService.ProvideUsernamePassword:output_type -> vcassist.services.vcmoodle.v1.ProvideUsernamePasswordResponse
	10, // 14: vcassist.services.vcmoodle.v1.MoodleService.GetCourses:output_type -> vcassist.services.vcmoodle.v1.GetCoursesResponse
	16, // 15: vcassist.services.vcmoodle.v1.MoodleService.RefreshCourses:output_type -> vcassist.services.vcmoodle.v1.RefreshCoursesResponse
	12, // 16: vcassist.services.vcmoodle.v1.MoodleService.GetChapterContent:output_type -> vcassist.services.vcmoodle.v1.GetChapterContentResponse
	14, // 17: vcassist.services.vcmoodle.v1.MoodleService.GetFileContent:output_type -> vcassist.services.vcmoodle.v1.GetFileContentResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_vcassist_services_vcmoodle_v1_api_proto_init() }
func file_vcassist_services_vcmoodle_v1_api_proto_init() {
	if File_vcassist_services_vcmoodle_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAuthStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAuthStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ProvideUsernamePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ProvideUsernamePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Chapter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Section); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Course); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetCoursesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetCoursesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetChapterContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetChapterContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetFileContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetFileContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RefreshCoursesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcassist_services_vcmoodle_v1_api_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RefreshCoursesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vcassist_services_vcmoodle_v1_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vcassist_services_vcmoodle_v1_api_proto_goTypes,
		DependencyIndexes: file_vcassist_services_vcmoodle_v1_api_proto_depIdxs,
		EnumInfos:         file_vcassist_services_vcmoodle_v1_api_proto_enumTypes,
		MessageInfos:      file_vcassist_services_vcmoodle_v1_api_proto_msgTypes,
	}.Build()
	File_vcassist_services_vcmoodle_v1_api_proto = out.File
	file_vcassist_services_vcmoodle_v1_api_proto_rawDesc = nil
	file_vcassist_services_vcmoodle_v1_api_proto_goTypes = nil
	file_vcassist_services_vcmoodle_v1_api_proto_depIdxs = nil
}
