// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file vcassist/services/vcmoodle/v1/api.proto (package vcassist.services.vcmoodle.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAuthStatusRequest, GetAuthStatusResponse, GetChapterContentRequest, GetChapterContentResponse, GetCoursesRequest, GetCoursesResponse, GetFileContentRequest, GetFileContentResponse, GetSessionRequest, GetSessionResponse, ProvideUsernamePasswordRequest, ProvideUsernamePasswordResponse, RefreshCoursesRequest, RefreshCoursesResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service vcassist.services.vcmoodle.v1.MoodleService
 */
export const MoodleService = {
  typeName: "vcassist.services.vcmoodle.v1.MoodleService",
  methods: {
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.GetAuthStatus
     */
    getAuthStatus: {
      name: "GetAuthStatus",
      I: GetAuthStatusRequest,
      O: GetAuthStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.ProvideUsernamePassword
     */
    provideUsernamePassword: {
      name: "ProvideUsernamePassword",
      I: ProvideUsernamePasswordRequest,
      O: ProvideUsernamePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.GetSession
     */
    getSession: {
      name: "GetSession",
      I: GetSessionRequest,
      O: GetSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.GetCourses
     */
    getCourses: {
      name: "GetCourses",
      I: GetCoursesRequest,
      O: GetCoursesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.RefreshCourses
     */
    refreshCourses: {
      name: "RefreshCourses",
      I: RefreshCoursesRequest,
      O: RefreshCoursesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.GetChapterContent
     */
    getChapterContent: {
      name: "GetChapterContent",
      I: GetChapterContentRequest,
      O: GetChapterContentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.vcmoodle.v1.MoodleService.GetFileContent
     */
    getFileContent: {
      name: "GetFileContent",
      I: GetFileContentRequest,
      O: GetFileContentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

