// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file services/linker/api/api.proto (package services.linker.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddExplicitLinkRequest, AddExplicitLinkResponse, DeleteExplicitLinkRequest, DeleteExplicitLinkResponse, GetExplicitLinksRequest, GetExplicitLinksResponse, GetKnownKeysRequest, GetKnownKeysResponse, GetKnownSetsRequest, GetKnownSetsResponse, LinkRequest, LinkResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service services.linker.api.LinkerService
 */
export const LinkerService = {
  typeName: "services.linker.api.LinkerService",
  methods: {
    /**
     * @generated from rpc services.linker.api.LinkerService.GetExplicitLinks
     */
    getExplicitLinks: {
      name: "GetExplicitLinks",
      I: GetExplicitLinksRequest,
      O: GetExplicitLinksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc services.linker.api.LinkerService.AddExplicitLink
     */
    addExplicitLink: {
      name: "AddExplicitLink",
      I: AddExplicitLinkRequest,
      O: AddExplicitLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc services.linker.api.LinkerService.DeleteExplicitLink
     */
    deleteExplicitLink: {
      name: "DeleteExplicitLink",
      I: DeleteExplicitLinkRequest,
      O: DeleteExplicitLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc services.linker.api.LinkerService.Link
     */
    link: {
      name: "Link",
      I: LinkRequest,
      O: LinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc services.linker.api.LinkerService.GetKnownSets
     */
    getKnownSets: {
      name: "GetKnownSets",
      I: GetKnownSetsRequest,
      O: GetKnownSetsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc services.linker.api.LinkerService.GetKnownKeys
     */
    getKnownKeys: {
      name: "GetKnownKeys",
      I: GetKnownKeysRequest,
      O: GetKnownKeysResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

