// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cmd/powerschool_api/api/api.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	api "vcassist-backend/cmd/powerschool_api/api"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PowerschoolServiceName is the fully-qualified name of the PowerschoolService service.
	PowerschoolServiceName = "cmd.powerschool_api.api.PowerschoolService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PowerschoolServiceGetOAuthProcedure is the fully-qualified name of the PowerschoolService's
	// GetOAuth RPC.
	PowerschoolServiceGetOAuthProcedure = "/cmd.powerschool_api.api.PowerschoolService/GetOAuth"
	// PowerschoolServiceProvideOAuthProcedure is the fully-qualified name of the PowerschoolService's
	// ProvideOAuth RPC.
	PowerschoolServiceProvideOAuthProcedure = "/cmd.powerschool_api.api.PowerschoolService/ProvideOAuth"
	// PowerschoolServiceGetStudentDataProcedure is the fully-qualified name of the PowerschoolService's
	// GetStudentData RPC.
	PowerschoolServiceGetStudentDataProcedure = "/cmd.powerschool_api.api.PowerschoolService/GetStudentData"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	powerschoolServiceServiceDescriptor              = api.File_cmd_powerschool_api_api_api_proto.Services().ByName("PowerschoolService")
	powerschoolServiceGetOAuthMethodDescriptor       = powerschoolServiceServiceDescriptor.Methods().ByName("GetOAuth")
	powerschoolServiceProvideOAuthMethodDescriptor   = powerschoolServiceServiceDescriptor.Methods().ByName("ProvideOAuth")
	powerschoolServiceGetStudentDataMethodDescriptor = powerschoolServiceServiceDescriptor.Methods().ByName("GetStudentData")
)

// PowerschoolServiceClient is a client for the cmd.powerschool_api.api.PowerschoolService service.
type PowerschoolServiceClient interface {
	GetOAuth(context.Context, *connect.Request[api.GetOAuthRequest]) (*connect.Response[api.GetOAuthResponse], error)
	ProvideOAuth(context.Context, *connect.Request[api.ProvideOAuthRequest]) (*connect.Response[api.ProvideOAuthResponse], error)
	GetStudentData(context.Context, *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error)
}

// NewPowerschoolServiceClient constructs a client for the
// cmd.powerschool_api.api.PowerschoolService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPowerschoolServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PowerschoolServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &powerschoolServiceClient{
		getOAuth: connect.NewClient[api.GetOAuthRequest, api.GetOAuthResponse](
			httpClient,
			baseURL+PowerschoolServiceGetOAuthProcedure,
			connect.WithSchema(powerschoolServiceGetOAuthMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		provideOAuth: connect.NewClient[api.ProvideOAuthRequest, api.ProvideOAuthResponse](
			httpClient,
			baseURL+PowerschoolServiceProvideOAuthProcedure,
			connect.WithSchema(powerschoolServiceProvideOAuthMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getStudentData: connect.NewClient[api.GetStudentDataRequest, api.GetStudentDataResponse](
			httpClient,
			baseURL+PowerschoolServiceGetStudentDataProcedure,
			connect.WithSchema(powerschoolServiceGetStudentDataMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// powerschoolServiceClient implements PowerschoolServiceClient.
type powerschoolServiceClient struct {
	getOAuth       *connect.Client[api.GetOAuthRequest, api.GetOAuthResponse]
	provideOAuth   *connect.Client[api.ProvideOAuthRequest, api.ProvideOAuthResponse]
	getStudentData *connect.Client[api.GetStudentDataRequest, api.GetStudentDataResponse]
}

// GetOAuth calls cmd.powerschool_api.api.PowerschoolService.GetOAuth.
func (c *powerschoolServiceClient) GetOAuth(ctx context.Context, req *connect.Request[api.GetOAuthRequest]) (*connect.Response[api.GetOAuthResponse], error) {
	return c.getOAuth.CallUnary(ctx, req)
}

// ProvideOAuth calls cmd.powerschool_api.api.PowerschoolService.ProvideOAuth.
func (c *powerschoolServiceClient) ProvideOAuth(ctx context.Context, req *connect.Request[api.ProvideOAuthRequest]) (*connect.Response[api.ProvideOAuthResponse], error) {
	return c.provideOAuth.CallUnary(ctx, req)
}

// GetStudentData calls cmd.powerschool_api.api.PowerschoolService.GetStudentData.
func (c *powerschoolServiceClient) GetStudentData(ctx context.Context, req *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error) {
	return c.getStudentData.CallUnary(ctx, req)
}

// PowerschoolServiceHandler is an implementation of the cmd.powerschool_api.api.PowerschoolService
// service.
type PowerschoolServiceHandler interface {
	GetOAuth(context.Context, *connect.Request[api.GetOAuthRequest]) (*connect.Response[api.GetOAuthResponse], error)
	ProvideOAuth(context.Context, *connect.Request[api.ProvideOAuthRequest]) (*connect.Response[api.ProvideOAuthResponse], error)
	GetStudentData(context.Context, *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error)
}

// NewPowerschoolServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPowerschoolServiceHandler(svc PowerschoolServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	powerschoolServiceGetOAuthHandler := connect.NewUnaryHandler(
		PowerschoolServiceGetOAuthProcedure,
		svc.GetOAuth,
		connect.WithSchema(powerschoolServiceGetOAuthMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	powerschoolServiceProvideOAuthHandler := connect.NewUnaryHandler(
		PowerschoolServiceProvideOAuthProcedure,
		svc.ProvideOAuth,
		connect.WithSchema(powerschoolServiceProvideOAuthMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	powerschoolServiceGetStudentDataHandler := connect.NewUnaryHandler(
		PowerschoolServiceGetStudentDataProcedure,
		svc.GetStudentData,
		connect.WithSchema(powerschoolServiceGetStudentDataMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cmd.powerschool_api.api.PowerschoolService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PowerschoolServiceGetOAuthProcedure:
			powerschoolServiceGetOAuthHandler.ServeHTTP(w, r)
		case PowerschoolServiceProvideOAuthProcedure:
			powerschoolServiceProvideOAuthHandler.ServeHTTP(w, r)
		case PowerschoolServiceGetStudentDataProcedure:
			powerschoolServiceGetStudentDataHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPowerschoolServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPowerschoolServiceHandler struct{}

func (UnimplementedPowerschoolServiceHandler) GetOAuth(context.Context, *connect.Request[api.GetOAuthRequest]) (*connect.Response[api.GetOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cmd.powerschool_api.api.PowerschoolService.GetOAuth is not implemented"))
}

func (UnimplementedPowerschoolServiceHandler) ProvideOAuth(context.Context, *connect.Request[api.ProvideOAuthRequest]) (*connect.Response[api.ProvideOAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cmd.powerschool_api.api.PowerschoolService.ProvideOAuth is not implemented"))
}

func (UnimplementedPowerschoolServiceHandler) GetStudentData(context.Context, *connect.Request[api.GetStudentDataRequest]) (*connect.Response[api.GetStudentDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cmd.powerschool_api.api.PowerschoolService.GetStudentData is not implemented"))
}
