package linker

import (
	"fmt"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
)

func TestCreateImplicitLinks(t *testing.T) {
	testCases := []struct {
		left  []string
		right []string
		// if ImplicitLink.Correlation == 0
		// the test will not assert the correlation to be equal
		expected []ImplicitLink
	}{
		{
			left:  []string{"a", "b", "c"},
			right: []string{"a", "b"},
			expected: []ImplicitLink{
				{
					Left:        "a",
					Right:       "a",
					Correlation: 1,
				},
				{
					Left:        "b",
					Right:       "b",
					Correlation: 1,
				},
			},
		},
		{
			left:  []string{"foo", "bar", "baz"},
			right: []string{"foob", "bar", "barr"},
			expected: []ImplicitLink{
				{
					Left:        "bar",
					Right:       "bar",
					Correlation: 1,
				},
				{
					Left:  "baz",
					Right: "barr",
				},
				{
					Left:  "foo",
					Right: "foob",
				},
			},
		},
		{
			left:     []string{"foo", "bar", "baz"},
			right:    []string{},
			expected: nil,
		},
		{
			left:     []string{},
			right:    []string{},
			expected: nil,
		},
		{
			left:  []string{"foo", "bar", "baz"},
			right: []string{"baa"},
			expected: []ImplicitLink{
				{
					Left:  "bar",
					Right: "baa",
				},
			},
		},
		{
			left: []string{
				// weight names
				"3D Animation",
				"AP African American Studies",
				"AP Art History",
				"AP Biology",
				"AP Calculus AB",
				"AP Calculus BC",
				"AP Chemistry",
				"AP Chinese Language and Culture",
				"AP Comp Sci Principles (CodeHS)",
				"AP Computer Science A (CodeHS)",
				"AP English Language and Comp",
				"AP English Literature and Comp",
				"AP Environmental Science",
				"AP Human Geography",
				"AP Latin",
				"AP Microeconomics",
				"AP Music Theory",
				"AP Physics 1",
				"AP Physics C: Electricity & Magnetism",
				"AP Physics C: Mechanics",
				"AP Spanish Language & Culture",
				"AP Statistics",
				"AP Studio Art: 2D Design",
				"AP Studio Art: Drawing",
				"AP US Government & Politics",
				"AP US History",
				"ASB Student Government",
				"Adv Design & Production Intern",
				"Advanced 3D Animation",
				"Advanced Applied Filmmaking (H)",
				"Advanced Data Analysis",
				"Aerospace Engineering",
				"African American Literature",
				"Algebra I",
				"Algebra II",
				"Algebra II (H)",
				"American Literature",
				"American Sign Language I",
				"American Sign Language II",
				"American Sign Language III",
				"American Sign Language IV (H)",
				"Anatomy/Physiology",
				"Anatomy/Physiology (H)",
				"Applied Filmmaking",
				"Art I",
				"Art II",
				"Art III (H)",
				"Art of Filmmaking",
				"Astronomy",
				"Biology",
				"Biology (H)",
				"British Literature",
				"Business Fundamentals",
				"Calculus",
				"Ceramics I",
				"Ceramics II",
				"Ceramics III (H)",
				"Chamber Ensemble",
				"Chemistry",
				"Chemistry (H)",
				"Christian Practice & Belief",
				"Christianity & Leadership",
				"Conservatory Chorus",
				"Dance Technique I",
				"Dance Technique II",
				"Dance Technique III",
				"Dance Technique III (H)",
				"Debate",
				"Economics",
				"English 10",
				"English 10 (H)",
				"English 9",
				"English 9 (H)",
				"Entrepreneurship (H)",
				"Football Performance",
				"Foundations of Baseball",
				"Foundations of Water Polo",
				"French I",
				"French II",
				"French III",
				"French IV (H)",
				"Geometry",
				"Geometry (H)",
				"Graphic Design",
				"Guitar II",
				"Guitar III",
				"Hip Hop I",
				"Hip Hop II",
				"Hip Hop III",
				"Hip Hop III (H)",
				"History and Music",
				"Indoor Sports Performance (Boys)",
				"Indoor Sports Performance (Girls)",
				"Integrated Science",
				"Intro to Computer Prog (CodeHS)",
				"Intro to Engineering Design",
				"Intro to Guitar & Electric Bass",
				"Jazz Ensemble (H)",
				"Jazz Lab",
				"Latin I",
				"Latin II",
				"Latin III",
				"Latin III (H)",
				"Lifetime Fitness (Boys)",
				"Lifetime Fitness (Girls)",
				"Mandarin I",
				"Mandarin II",
				"Mandarin III",
				"Mandarin IV (H)",
				"Marine Biology",
				"Mathematics of Financial Analysis",
				"Modern World History",
				"Modern World History (H)",
				"Multi-Variable Calculus",
				"New Testament Studies",
				"Outdoor Sports Performance (B)",
				"Outdoor Sports Performance (G)",
				"PE Extension",
				"Percussion Ensemble",
				"Personal Finance & Stewardship",
				"Philosophy in Literature",
				"Philosophy of Religion",
				"Photographic Design I",
				"Photographic Design Studio (H)",
				"Physics",
				"Piano I",
				"Piano II",
				"Piano III",
				"Principles of Engineering",
				"REACH",
				"REACH II",
				"Scientific Research",
				"Service Learning: Justice",
				"Service Learning: Mentoring",
				"Service Learning: Missions",
				"Service Learning: Outreach",
				"Spanish I",
				"Spanish II",
				"Spanish III",
				"Spanish III (H)",
				"Spanish IV",
				"Speech",
				"Statistics",
				"String Ensemble",
				"Tech Theatre I",
				"Tech Theatre II",
				"Tech Theatre III (H)",
				"Theatre I",
				"Theatre II",
				"Theatre III",
				"Theatre IV (H)",
				"Traditional Animation Techniques",
				"Trig/Pre-Calculus AB",
				"Trig/Pre-Calculus BC (H)",
				"Trigonometry/Pre-Calculus",
				"US Government",
				"US History",
				"Wind Ensemble",
				"Wisdom for Leaders",
				"Worship Choir",
				"Yearbook",
				"iPad Tech Support Internship",
			},
			right: []string{
				"AP Biology",
				"AP Calculus AB",
				"AP Calculus BC",
				"AP Chemistry",
				"AP Comp Sci Principles (CodeHS)",
				"AP Computer Science A (CodeHS)",
				"AP English Language and Comp",
				"AP English Literature and Comp",
				"AP Environmental Science",
				"AP Human Geography",
				"AP Microeconomics",
				"AP Music Theory",
				"AP Physics 1",
				"AP Physics C: Mechanics",
				"AP Psychology",
				"AP Spanish Language & Culture",
				"AP Statistics",
				"AP US Government & Politics",
				"AP US History",
				"Advanced Data Analysis (H)",
				"African American Literature",
				"Algebra I",
				"Algebra II",
				"Algebra II (H)",
				"Algebra Readiness",
				"American Sign Language III",
				"Anatomy/Physiology",
				"Anatomy/Physiology (H)",
				"Applied English & Bible Fundamentals",
				"Art I",
				"Band II",
				"Bible 6",
				"Bible 8",
				"Biblical Interpretation",
				"Biology (H)",
				"Boys PE 7/8",
				"British Literature",
				"Business Fundamentals",
				"Calculus (H)",
				"Ceramics I",
				"Chapel",
				"Chemistry",
				"Chemistry (H)",
				"Christian Doctrine and Practice",
				"Community Outreach Fellowship",
				"Data Structures and Algorithms (H)",
				"Drama I",
				"Earth Science",
				"English 10 (H)",
				"English 6",
				"English 8",
				"English 9 (H)",
				"Entrepreneurship (H)",
				"Forensic Science",
				"French I",
				"French II",
				"Geometry (H)",
				"Girls PE 6",
				"Graphic Design",
				"History 6",
				"History 8",
				"Indoor Sports Performance (Boys)",
				"Indoor Sports Performance (Girls)",
				"Intro to Biblical Interpretation",
				"Intro to Clay",
				"Intro to JH Photo",
				"Intro to Technology",
				"Latin II",
				"Lifetime Fitness (Boys)",
				"Lifetime Fitness (Girls)",
				"Mandarin III",
				"Modern World History",
				"Multi-Variable Calculus (H)",
				"New Testament Studies",
				"Ocean Discovery",
				"Open Period",
				"PLTW Principles of Engineering (H)",
				"PLTW Space and Electricity",
				"Personal Finance & Stewardship",
				"Philosophy In Literature (H)",
				"Philosophy of Religion",
				"Photographic Design I",
				"Physical Science",
				"Physics",
				"Physics (H)",
				"Pre-Algebra",
				"Pre-Calculus",
				"Pre-Calculus (H)",
				"Pre-Calculus Accelerated",
				"Screenwriting and Literature",
				"Service Learning:  Mentoring",
				"Service Learning: Justice",
				"Service Learning: Missions",
				"Social Innovation (H)",
				"Spanish I",
				"Spanish III (H)",
				"Statistics (H)",
				"Symphonic Band",
				"Teacher's Aid",
				"Tech Theatre III (H)",
				"Theatre II",
				"US Government",
				"US History",
				"Unscheduled",
				"WarriorTime",
				"Worship & Production Arts",
			},
			expected: []ImplicitLink{
				{Left: "AP Biology", Right: "AP Biology", Correlation: 1.000000},
				{Left: "AP Calculus AB", Right: "AP Calculus AB", Correlation: 1.000000},
				{Left: "AP Calculus BC", Right: "AP Calculus BC", Correlation: 1.000000},
				{Left: "AP Chemistry", Right: "AP Chemistry", Correlation: 1.000000},
				{Left: "AP Comp Sci Principles (CodeHS)", Right: "AP Comp Sci Principles (CodeHS)", Correlation: 1.000000},
				{Left: "AP Computer Science A (CodeHS)", Right: "AP Computer Science A (CodeHS)", Correlation: 1.000000},
				{Left: "AP English Language and Comp", Right: "AP English Language and Comp", Correlation: 1.000000},
				{Left: "AP English Literature and Comp", Right: "AP English Literature and Comp", Correlation: 1.000000},
				{Left: "AP Environmental Science", Right: "AP Environmental Science", Correlation: 1.000000},
				{Left: "AP Human Geography", Right: "AP Human Geography", Correlation: 1.000000},
				{Left: "AP Microeconomics", Right: "AP Microeconomics", Correlation: 1.000000},
				{Left: "AP Music Theory", Right: "AP Music Theory", Correlation: 1.000000},
				{Left: "AP Physics 1", Right: "AP Physics 1", Correlation: 1.000000},
				{Left: "AP Physics C: Mechanics", Right: "AP Physics C: Mechanics", Correlation: 1.000000},
				{Left: "AP Spanish Language & Culture", Right: "AP Spanish Language & Culture", Correlation: 1.000000},
				{Left: "AP Statistics", Right: "AP Statistics", Correlation: 1.000000},
				{Left: "AP US Government & Politics", Right: "AP US Government & Politics", Correlation: 1.000000},
				{Left: "AP US History", Right: "AP US History", Correlation: 1.000000},
				{Left: "African American Literature", Right: "African American Literature", Correlation: 1.000000},
				{Left: "Algebra I", Right: "Algebra I", Correlation: 1.000000},
				{Left: "Algebra II", Right: "Algebra II", Correlation: 1.000000},
				{Left: "Algebra II (H)", Right: "Algebra II (H)", Correlation: 1.000000},
				{Left: "American Sign Language III", Right: "American Sign Language III", Correlation: 1.000000},
				{Left: "Anatomy/Physiology", Right: "Anatomy/Physiology", Correlation: 1.000000},
				{Left: "Anatomy/Physiology (H)", Right: "Anatomy/Physiology (H)", Correlation: 1.000000},
				{Left: "Art I", Right: "Art I", Correlation: 1.000000},
				{Left: "Biology (H)", Right: "Biology (H)", Correlation: 1.000000},
				{Left: "British Literature", Right: "British Literature", Correlation: 1.000000},
				{Left: "Business Fundamentals", Right: "Business Fundamentals", Correlation: 1.000000},
				{Left: "Ceramics I", Right: "Ceramics I", Correlation: 1.000000},
				{Left: "Chemistry", Right: "Chemistry", Correlation: 1.000000},
				{Left: "Chemistry (H)", Right: "Chemistry (H)", Correlation: 1.000000},
				{Left: "English 10 (H)", Right: "English 10 (H)", Correlation: 1.000000},
				{Left: "English 9 (H)", Right: "English 9 (H)", Correlation: 1.000000},
				{Left: "Entrepreneurship (H)", Right: "Entrepreneurship (H)", Correlation: 1.000000},
				{Left: "French I", Right: "French I", Correlation: 1.000000},
				{Left: "French II", Right: "French II", Correlation: 1.000000},
				{Left: "Geometry (H)", Right: "Geometry (H)", Correlation: 1.000000},
				{Left: "Graphic Design", Right: "Graphic Design", Correlation: 1.000000},
				{Left: "Indoor Sports Performance (Boys)", Right: "Indoor Sports Performance (Boys)", Correlation: 1.000000},
				{Left: "Indoor Sports Performance (Girls)", Right: "Indoor Sports Performance (Girls)", Correlation: 1.000000},
				{Left: "Latin II", Right: "Latin II", Correlation: 1.000000},
				{Left: "Lifetime Fitness (Boys)", Right: "Lifetime Fitness (Boys)", Correlation: 1.000000},
				{Left: "Lifetime Fitness (Girls)", Right: "Lifetime Fitness (Girls)", Correlation: 1.000000},
				{Left: "Mandarin III", Right: "Mandarin III", Correlation: 1.000000},
				{Left: "Modern World History", Right: "Modern World History", Correlation: 1.000000},
				{Left: "New Testament Studies", Right: "New Testament Studies", Correlation: 1.000000},
				{Left: "Personal Finance & Stewardship", Right: "Personal Finance & Stewardship", Correlation: 1.000000},
				{Left: "Philosophy of Religion", Right: "Philosophy of Religion", Correlation: 1.000000},
				{Left: "Photographic Design I", Right: "Photographic Design I", Correlation: 1.000000},
				{Left: "Physics", Right: "Physics", Correlation: 1.000000},
				{Left: "Service Learning: Justice", Right: "Service Learning: Justice", Correlation: 1.000000},
				{Left: "Service Learning: Missions", Right: "Service Learning: Missions", Correlation: 1.000000},
				{Left: "Spanish I", Right: "Spanish I", Correlation: 1.000000},
				{Left: "Spanish III (H)", Right: "Spanish III (H)", Correlation: 1.000000},
				{Left: "Tech Theatre III (H)", Right: "Tech Theatre III (H)", Correlation: 1.000000},
				{Left: "Theatre II", Right: "Theatre II", Correlation: 1.000000},
				{Left: "US Government", Right: "US Government", Correlation: 1.000000},
				{Left: "US History", Right: "US History", Correlation: 1.000000},
				{Left: "Service Learning: Mentoring", Right: "Service Learning:  Mentoring", Correlation: 0.992857},
				{Left: "Multi-Variable Calculus", Right: "Multi-Variable Calculus (H)", Correlation: 0.970370},
				{Left: "Advanced Data Analysis", Right: "Advanced Data Analysis (H)", Correlation: 0.969231},
				{Left: "English 9", Right: "English 6", Correlation: 0.955556},
				{Left: "Statistics", Right: "Statistics (H)", Correlation: 0.942857},
				{Left: "Philosophy in Literature", Right: "Philosophy In Literature (H)", Correlation: 0.938561},
				{Left: "English 10", Right: "English 8", Correlation: 0.937778},
				{Left: "Calculus", Right: "Calculus (H)", Correlation: 0.933333},
				{Left: "History and Music", Right: "History 8", Correlation: 0.871895},
				{Left: "Trig/Pre-Calculus BC (H)", Right: "Pre-Calculus (H)", Correlation: 0.868056},
				{Left: "Christian Practice & Belief", Right: "Christian Doctrine and Practice", Correlation: 0.850353},
				{Left: "Principles of Engineering", Right: "PLTW Principles of Engineering (H)", Correlation: 0.848588},
				{Left: "Worship Choir", Right: "Worship & Production Arts", Correlation: 0.839049},
				{Left: "Trig/Pre-Calculus AB", Right: "Pre-Calculus", Correlation: 0.838889},
				{Left: "Applied Filmmaking", Right: "Applied English & Bible Fundamentals", Correlation: 0.829167},
				{Left: "Intro to Guitar & Electric Bass", Right: "Intro to Biblical Interpretation", Correlation: 0.828639},
				{Left: "Intro to Computer Prog (CodeHS)", Right: "Intro to JH Photo", Correlation: 0.826457},
				{Left: "Mandarin II", Right: "Band II", Correlation: 0.800866},
				{Left: "Service Learning: Outreach", Right: "Screenwriting and Literature", Correlation: 0.738736},
				{Left: "Ceramics II", Right: "Drama I", Correlation: 0.722944},
				{Left: "Theatre I", Right: "Teacher's Aid", Correlation: 0.676842},
				{Left: "Intro to Engineering Design", Right: "Intro to Clay", Correlation: 0.675214},
				{Left: "Integrated Science", Right: "Earth Science", Correlation: 0.667573},
				{Left: "AP Physics C: Electricity & Magnetism", Right: "PLTW Space and Electricity", Correlation: 0.665220},
				{Left: "Mandarin IV (H)", Right: "Social Innovation (H)", Correlation: 0.661472},
				{Left: "French III", Right: "Forensic Science", Correlation: 0.658333},
				{Left: "Photographic Design Studio (H)", Right: "Data Structures and Algorithms (H)", Correlation: 0.645565},
				{Left: "Ceramics III (H)", Right: "Physics (H)", Correlation: 0.643669},
				{Left: "Chamber Ensemble", Right: "Chapel", Correlation: 0.638889},
				{Left: "Astronomy", Right: "History 6", Correlation: 0.637037},
				{Left: "Debate", Right: "Algebra Readiness", Correlation: 0.633987},
				{Left: "Economics", Right: "Ocean Discovery", Correlation: 0.633333},
				{Left: "Marine Biology", Right: "Intro to Technology", Correlation: 0.631440},
				{Left: "AP Art History", Right: "AP Psychology", Correlation: 0.630037},
				{Left: "Christianity & Leadership", Right: "Community Outreach Fellowship", Correlation: 0.626408},
				{Left: "Spanish IV", Right: "Symphonic Band", Correlation: 0.620635},
				{Left: "Biology", Right: "Bible 6", Correlation: 0.619048},
				{Left: "Guitar II", Right: "Girls PE 6", Correlation: 0.614815},
				{Left: "Wind Ensemble", Right: "Unscheduled", Correlation: 0.613442},
				{Left: "Football Performance", Right: "Biblical Interpretation", Correlation: 0.610201},
				{Left: "Piano I", Right: "Physical Science", Correlation: 0.607143},
				{Left: "AP Chinese Language and Culture", Right: "Pre-Calculus Accelerated", Correlation: 0.602599},
				{Left: "Trigonometry/Pre-Calculus", Right: "WarriorTime", Correlation: 0.599091},
				{Left: "Speech", Right: "Open Period", Correlation: 0.590909},
				{Left: "Aerospace Engineering", Right: "Pre-Algebra", Correlation: 0.561328},
				{Left: "Scientific Research", Right: "Bible 8", Correlation: 0.528822},
				{Left: "Foundations of Baseball", Right: "Boys PE 7/8", Correlation: 0.512516},
			},
		},
	}

	for _, test := range testCases {
		links := CreateImplicitLinks(test.left, test.right)

		for _, l := range links {
			fmt.Printf("%-40s %-40s %f\n", l.Left, l.Right, l.Correlation)
		}

		diff := cmp.Diff(
			test.expected,
			links,
			cmpopts.SortSlices(func(a, b ImplicitLink) bool {
				return a.Left < b.Left
			}),
			cmpopts.IgnoreFields(ImplicitLink{}, "Correlation"),
		)
		if diff != "" {
			t.Fatal(diff)
		}
	}
}
