// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type GradeSnapshot struct {
	UserCourseID int64
	Time         int64
	Value        float64
}

type UserCourse struct {
	ID     int64
	User   string
	Course string
}
