// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file vcassist/services/sis/v1/api.proto (package vcassist.services.sis.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCredentialStatusRequest, GetCredentialStatusResponse, GetDataRequest, GetDataResponse, ProvideCredentialRequest, ProvideCredentialResponse, RefreshDataRequest, RefreshDataResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SIS stands for "school information service"
 *
 * @generated from service vcassist.services.sis.v1.SIService
 */
export const SIService = {
  typeName: "vcassist.services.sis.v1.SIService",
  methods: {
    /**
     * @generated from rpc vcassist.services.sis.v1.SIService.GetCredentialStatus
     */
    getCredentialStatus: {
      name: "GetCredentialStatus",
      I: GetCredentialStatusRequest,
      O: GetCredentialStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.sis.v1.SIService.ProvideCredential
     */
    provideCredential: {
      name: "ProvideCredential",
      I: ProvideCredentialRequest,
      O: ProvideCredentialResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.sis.v1.SIService.GetData
     */
    getData: {
      name: "GetData",
      I: GetDataRequest,
      O: GetDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc vcassist.services.sis.v1.SIService.RefreshData
     */
    refreshData: {
      name: "RefreshData",
      I: RefreshDataRequest,
      O: RefreshDataResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

