// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type KnownCourse struct {
	Guid             string
	Name             string
	Period           sql.NullString
	Teacherfirstname sql.NullString
	Teacherlastname  sql.NullString
	Teacheremail     sql.NullString
	Room             sql.NullString
}

type OAuthToken struct {
	Studentid string
	Token     string
	Expiresat int64
}

type Student struct {
	ID string
}

type StudentDatum struct {
	Studentid string
	Cached    []byte
	Createdat int64
}
