// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file vcassist/moodle/v1/api.proto (package vcassist.moodle.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChapterContentRequest, ChapterContentResponse, LessonPlansRequest, LessonPlansResponse, RefreshRequest, RefreshResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service vcassist.moodle.v1.MoodleService
 */
export const MoodleService = {
  typeName: "vcassist.moodle.v1.MoodleService",
  methods: {
    /**
     * @generated from rpc vcassist.moodle.v1.MoodleService.Refresh
     */
    refresh: {
      name: "Refresh",
      I: RefreshRequest,
      O: RefreshResponse,
      kind: MethodKind.Unary,
    },
    /**
     * LessonPlans has no server-side caching, it is up to the clients to cache this request.
     *
     * @generated from rpc vcassist.moodle.v1.MoodleService.LessonPlans
     */
    lessonPlans: {
      name: "LessonPlans",
      I: LessonPlansRequest,
      O: LessonPlansResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ChapterContent has no server-side caching, it is up to the clients to cache this request.
     *
     * @generated from rpc vcassist.moodle.v1.MoodleService.ChapterContent
     */
    chapterContent: {
      name: "ChapterContent",
      I: ChapterContentRequest,
      O: ChapterContentResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

