// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package servicedb

import (
	"database/sql"
	"time"
)

type Gradesnapshot struct {
	SeriesID int64
	Value    float64
}

type GradesnapshotSeries struct {
	ID                   int64
	PowerschoolAccountID int64
	CourseID             string
	StartTime            time.Time
}

type MoodleAccount struct {
	ID       int64
	Username string
}

type PowerschoolAccount struct {
	ID    int64
	Email string
}

type Token struct {
	Token                string
	MoodleAccountID      sql.NullInt64
	PowerschoolAccountID sql.NullInt64
}
