// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type ActiveToken struct {
	Token     string
	Useremail string
	Expiresat int64
}

type Parent struct {
	Parentemail string
	Useremail   string
}

type User struct {
	Email string
}

type VerificationCode struct {
	Code      string
	Useremail string
	Expiresat int64
}
