// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const createOAuth = `-- name: CreateOAuth :exec
insert into OAuth(namespace, id, token, refresh_url, client_id, expires_at) values (?, ?, ?, ?, ?, ?)
on conflict do update set
    token = EXCLUDED.token,
    refresh_url = EXCLUDED.refresh_url,
    client_id = EXCLUDED.client_id,
    expires_at = EXCLUDED.expires_at
`

type CreateOAuthParams struct {
	Namespace  string
	ID         string
	Token      string
	RefreshUrl string
	ClientID   string
	ExpiresAt  int64
}

func (q *Queries) CreateOAuth(ctx context.Context, arg CreateOAuthParams) error {
	_, err := q.db.ExecContext(ctx, createOAuth,
		arg.Namespace,
		arg.ID,
		arg.Token,
		arg.RefreshUrl,
		arg.ClientID,
		arg.ExpiresAt,
	)
	return err
}

const createUsernamePassword = `-- name: CreateUsernamePassword :exec
insert into UsernamePassword(namespace, id, username, password) values (?, ?, ?, ?)
on conflict do update set
    username = EXCLUDED.username,
    password = EXCLUDED.password
`

type CreateUsernamePasswordParams struct {
	Namespace string
	ID        string
	Username  string
	Password  string
}

func (q *Queries) CreateUsernamePassword(ctx context.Context, arg CreateUsernamePasswordParams) error {
	_, err := q.db.ExecContext(ctx, createUsernamePassword,
		arg.Namespace,
		arg.ID,
		arg.Username,
		arg.Password,
	)
	return err
}

const deleteOAuthBefore = `-- name: DeleteOAuthBefore :exec
delete from OAuth where expires_at < ?
`

func (q *Queries) DeleteOAuthBefore(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthBefore, expiresAt)
	return err
}

const getOAuth = `-- name: GetOAuth :one
select token, refresh_url, client_id, expires_at from OAuth where
namespace = ? and id = ?
`

type GetOAuthParams struct {
	Namespace string
	ID        string
}

type GetOAuthRow struct {
	Token      string
	RefreshUrl string
	ClientID   string
	ExpiresAt  int64
}

func (q *Queries) GetOAuth(ctx context.Context, arg GetOAuthParams) (GetOAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getOAuth, arg.Namespace, arg.ID)
	var i GetOAuthRow
	err := row.Scan(
		&i.Token,
		&i.RefreshUrl,
		&i.ClientID,
		&i.ExpiresAt,
	)
	return i, err
}

const getOAuthBefore = `-- name: GetOAuthBefore :many
select namespace, id, token, refresh_url, client_id, expires_at from OAuth where expires_at < ?
`

func (q *Queries) GetOAuthBefore(ctx context.Context, expiresAt int64) ([]OAuth, error) {
	rows, err := q.db.QueryContext(ctx, getOAuthBefore, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OAuth
	for rows.Next() {
		var i OAuth
		if err := rows.Scan(
			&i.Namespace,
			&i.ID,
			&i.Token,
			&i.RefreshUrl,
			&i.ClientID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsernamePassword = `-- name: GetUsernamePassword :one
select username, password from UsernamePassword where
namespace = ? and id = ?
`

type GetUsernamePasswordParams struct {
	Namespace string
	ID        string
}

type GetUsernamePasswordRow struct {
	Username string
	Password string
}

func (q *Queries) GetUsernamePassword(ctx context.Context, arg GetUsernamePasswordParams) (GetUsernamePasswordRow, error) {
	row := q.db.QueryRowContext(ctx, getUsernamePassword, arg.Namespace, arg.ID)
	var i GetUsernamePasswordRow
	err := row.Scan(&i.Username, &i.Password)
	return i, err
}
