// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vcassist/services/linker/v1/api.proto

package linkerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "vcassist-backend/proto/vcassist/services/linker/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LinkerServiceName is the fully-qualified name of the LinkerService service.
	LinkerServiceName = "vcassist.services.linker.v1.LinkerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LinkerServiceGetExplicitLinksProcedure is the fully-qualified name of the LinkerService's
	// GetExplicitLinks RPC.
	LinkerServiceGetExplicitLinksProcedure = "/vcassist.services.linker.v1.LinkerService/GetExplicitLinks"
	// LinkerServiceAddExplicitLinkProcedure is the fully-qualified name of the LinkerService's
	// AddExplicitLink RPC.
	LinkerServiceAddExplicitLinkProcedure = "/vcassist.services.linker.v1.LinkerService/AddExplicitLink"
	// LinkerServiceDeleteExplicitLinkProcedure is the fully-qualified name of the LinkerService's
	// DeleteExplicitLink RPC.
	LinkerServiceDeleteExplicitLinkProcedure = "/vcassist.services.linker.v1.LinkerService/DeleteExplicitLink"
	// LinkerServiceLinkProcedure is the fully-qualified name of the LinkerService's Link RPC.
	LinkerServiceLinkProcedure = "/vcassist.services.linker.v1.LinkerService/Link"
	// LinkerServiceLinkDetailProcedure is the fully-qualified name of the LinkerService's LinkDetail
	// RPC.
	LinkerServiceLinkDetailProcedure = "/vcassist.services.linker.v1.LinkerService/LinkDetail"
	// LinkerServiceGetKnownSetsProcedure is the fully-qualified name of the LinkerService's
	// GetKnownSets RPC.
	LinkerServiceGetKnownSetsProcedure = "/vcassist.services.linker.v1.LinkerService/GetKnownSets"
	// LinkerServiceGetKnownKeysProcedure is the fully-qualified name of the LinkerService's
	// GetKnownKeys RPC.
	LinkerServiceGetKnownKeysProcedure = "/vcassist.services.linker.v1.LinkerService/GetKnownKeys"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	linkerServiceServiceDescriptor                  = v1.File_vcassist_services_linker_v1_api_proto.Services().ByName("LinkerService")
	linkerServiceGetExplicitLinksMethodDescriptor   = linkerServiceServiceDescriptor.Methods().ByName("GetExplicitLinks")
	linkerServiceAddExplicitLinkMethodDescriptor    = linkerServiceServiceDescriptor.Methods().ByName("AddExplicitLink")
	linkerServiceDeleteExplicitLinkMethodDescriptor = linkerServiceServiceDescriptor.Methods().ByName("DeleteExplicitLink")
	linkerServiceLinkMethodDescriptor               = linkerServiceServiceDescriptor.Methods().ByName("Link")
	linkerServiceLinkDetailMethodDescriptor         = linkerServiceServiceDescriptor.Methods().ByName("LinkDetail")
	linkerServiceGetKnownSetsMethodDescriptor       = linkerServiceServiceDescriptor.Methods().ByName("GetKnownSets")
	linkerServiceGetKnownKeysMethodDescriptor       = linkerServiceServiceDescriptor.Methods().ByName("GetKnownKeys")
)

// LinkerServiceClient is a client for the vcassist.services.linker.v1.LinkerService service.
type LinkerServiceClient interface {
	GetExplicitLinks(context.Context, *connect.Request[v1.GetExplicitLinksRequest]) (*connect.Response[v1.GetExplicitLinksResponse], error)
	AddExplicitLink(context.Context, *connect.Request[v1.AddExplicitLinkRequest]) (*connect.Response[v1.AddExplicitLinkResponse], error)
	DeleteExplicitLink(context.Context, *connect.Request[v1.DeleteExplicitLinkRequest]) (*connect.Response[v1.DeleteExplicitLinkResponse], error)
	Link(context.Context, *connect.Request[v1.LinkRequest]) (*connect.Response[v1.LinkResponse], error)
	LinkDetail(context.Context, *connect.Request[v1.LinkDetailRequest]) (*connect.Response[v1.LinkDetailResponse], error)
	GetKnownSets(context.Context, *connect.Request[v1.GetKnownSetsRequest]) (*connect.Response[v1.GetKnownSetsResponse], error)
	GetKnownKeys(context.Context, *connect.Request[v1.GetKnownKeysRequest]) (*connect.Response[v1.GetKnownKeysResponse], error)
}

// NewLinkerServiceClient constructs a client for the vcassist.services.linker.v1.LinkerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLinkerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LinkerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &linkerServiceClient{
		getExplicitLinks: connect.NewClient[v1.GetExplicitLinksRequest, v1.GetExplicitLinksResponse](
			httpClient,
			baseURL+LinkerServiceGetExplicitLinksProcedure,
			connect.WithSchema(linkerServiceGetExplicitLinksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addExplicitLink: connect.NewClient[v1.AddExplicitLinkRequest, v1.AddExplicitLinkResponse](
			httpClient,
			baseURL+LinkerServiceAddExplicitLinkProcedure,
			connect.WithSchema(linkerServiceAddExplicitLinkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteExplicitLink: connect.NewClient[v1.DeleteExplicitLinkRequest, v1.DeleteExplicitLinkResponse](
			httpClient,
			baseURL+LinkerServiceDeleteExplicitLinkProcedure,
			connect.WithSchema(linkerServiceDeleteExplicitLinkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		link: connect.NewClient[v1.LinkRequest, v1.LinkResponse](
			httpClient,
			baseURL+LinkerServiceLinkProcedure,
			connect.WithSchema(linkerServiceLinkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		linkDetail: connect.NewClient[v1.LinkDetailRequest, v1.LinkDetailResponse](
			httpClient,
			baseURL+LinkerServiceLinkDetailProcedure,
			connect.WithSchema(linkerServiceLinkDetailMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getKnownSets: connect.NewClient[v1.GetKnownSetsRequest, v1.GetKnownSetsResponse](
			httpClient,
			baseURL+LinkerServiceGetKnownSetsProcedure,
			connect.WithSchema(linkerServiceGetKnownSetsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getKnownKeys: connect.NewClient[v1.GetKnownKeysRequest, v1.GetKnownKeysResponse](
			httpClient,
			baseURL+LinkerServiceGetKnownKeysProcedure,
			connect.WithSchema(linkerServiceGetKnownKeysMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// linkerServiceClient implements LinkerServiceClient.
type linkerServiceClient struct {
	getExplicitLinks   *connect.Client[v1.GetExplicitLinksRequest, v1.GetExplicitLinksResponse]
	addExplicitLink    *connect.Client[v1.AddExplicitLinkRequest, v1.AddExplicitLinkResponse]
	deleteExplicitLink *connect.Client[v1.DeleteExplicitLinkRequest, v1.DeleteExplicitLinkResponse]
	link               *connect.Client[v1.LinkRequest, v1.LinkResponse]
	linkDetail         *connect.Client[v1.LinkDetailRequest, v1.LinkDetailResponse]
	getKnownSets       *connect.Client[v1.GetKnownSetsRequest, v1.GetKnownSetsResponse]
	getKnownKeys       *connect.Client[v1.GetKnownKeysRequest, v1.GetKnownKeysResponse]
}

// GetExplicitLinks calls vcassist.services.linker.v1.LinkerService.GetExplicitLinks.
func (c *linkerServiceClient) GetExplicitLinks(ctx context.Context, req *connect.Request[v1.GetExplicitLinksRequest]) (*connect.Response[v1.GetExplicitLinksResponse], error) {
	return c.getExplicitLinks.CallUnary(ctx, req)
}

// AddExplicitLink calls vcassist.services.linker.v1.LinkerService.AddExplicitLink.
func (c *linkerServiceClient) AddExplicitLink(ctx context.Context, req *connect.Request[v1.AddExplicitLinkRequest]) (*connect.Response[v1.AddExplicitLinkResponse], error) {
	return c.addExplicitLink.CallUnary(ctx, req)
}

// DeleteExplicitLink calls vcassist.services.linker.v1.LinkerService.DeleteExplicitLink.
func (c *linkerServiceClient) DeleteExplicitLink(ctx context.Context, req *connect.Request[v1.DeleteExplicitLinkRequest]) (*connect.Response[v1.DeleteExplicitLinkResponse], error) {
	return c.deleteExplicitLink.CallUnary(ctx, req)
}

// Link calls vcassist.services.linker.v1.LinkerService.Link.
func (c *linkerServiceClient) Link(ctx context.Context, req *connect.Request[v1.LinkRequest]) (*connect.Response[v1.LinkResponse], error) {
	return c.link.CallUnary(ctx, req)
}

// LinkDetail calls vcassist.services.linker.v1.LinkerService.LinkDetail.
func (c *linkerServiceClient) LinkDetail(ctx context.Context, req *connect.Request[v1.LinkDetailRequest]) (*connect.Response[v1.LinkDetailResponse], error) {
	return c.linkDetail.CallUnary(ctx, req)
}

// GetKnownSets calls vcassist.services.linker.v1.LinkerService.GetKnownSets.
func (c *linkerServiceClient) GetKnownSets(ctx context.Context, req *connect.Request[v1.GetKnownSetsRequest]) (*connect.Response[v1.GetKnownSetsResponse], error) {
	return c.getKnownSets.CallUnary(ctx, req)
}

// GetKnownKeys calls vcassist.services.linker.v1.LinkerService.GetKnownKeys.
func (c *linkerServiceClient) GetKnownKeys(ctx context.Context, req *connect.Request[v1.GetKnownKeysRequest]) (*connect.Response[v1.GetKnownKeysResponse], error) {
	return c.getKnownKeys.CallUnary(ctx, req)
}

// LinkerServiceHandler is an implementation of the vcassist.services.linker.v1.LinkerService
// service.
type LinkerServiceHandler interface {
	GetExplicitLinks(context.Context, *connect.Request[v1.GetExplicitLinksRequest]) (*connect.Response[v1.GetExplicitLinksResponse], error)
	AddExplicitLink(context.Context, *connect.Request[v1.AddExplicitLinkRequest]) (*connect.Response[v1.AddExplicitLinkResponse], error)
	DeleteExplicitLink(context.Context, *connect.Request[v1.DeleteExplicitLinkRequest]) (*connect.Response[v1.DeleteExplicitLinkResponse], error)
	Link(context.Context, *connect.Request[v1.LinkRequest]) (*connect.Response[v1.LinkResponse], error)
	LinkDetail(context.Context, *connect.Request[v1.LinkDetailRequest]) (*connect.Response[v1.LinkDetailResponse], error)
	GetKnownSets(context.Context, *connect.Request[v1.GetKnownSetsRequest]) (*connect.Response[v1.GetKnownSetsResponse], error)
	GetKnownKeys(context.Context, *connect.Request[v1.GetKnownKeysRequest]) (*connect.Response[v1.GetKnownKeysResponse], error)
}

// NewLinkerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLinkerServiceHandler(svc LinkerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	linkerServiceGetExplicitLinksHandler := connect.NewUnaryHandler(
		LinkerServiceGetExplicitLinksProcedure,
		svc.GetExplicitLinks,
		connect.WithSchema(linkerServiceGetExplicitLinksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	linkerServiceAddExplicitLinkHandler := connect.NewUnaryHandler(
		LinkerServiceAddExplicitLinkProcedure,
		svc.AddExplicitLink,
		connect.WithSchema(linkerServiceAddExplicitLinkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	linkerServiceDeleteExplicitLinkHandler := connect.NewUnaryHandler(
		LinkerServiceDeleteExplicitLinkProcedure,
		svc.DeleteExplicitLink,
		connect.WithSchema(linkerServiceDeleteExplicitLinkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	linkerServiceLinkHandler := connect.NewUnaryHandler(
		LinkerServiceLinkProcedure,
		svc.Link,
		connect.WithSchema(linkerServiceLinkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	linkerServiceLinkDetailHandler := connect.NewUnaryHandler(
		LinkerServiceLinkDetailProcedure,
		svc.LinkDetail,
		connect.WithSchema(linkerServiceLinkDetailMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	linkerServiceGetKnownSetsHandler := connect.NewUnaryHandler(
		LinkerServiceGetKnownSetsProcedure,
		svc.GetKnownSets,
		connect.WithSchema(linkerServiceGetKnownSetsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	linkerServiceGetKnownKeysHandler := connect.NewUnaryHandler(
		LinkerServiceGetKnownKeysProcedure,
		svc.GetKnownKeys,
		connect.WithSchema(linkerServiceGetKnownKeysMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/vcassist.services.linker.v1.LinkerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LinkerServiceGetExplicitLinksProcedure:
			linkerServiceGetExplicitLinksHandler.ServeHTTP(w, r)
		case LinkerServiceAddExplicitLinkProcedure:
			linkerServiceAddExplicitLinkHandler.ServeHTTP(w, r)
		case LinkerServiceDeleteExplicitLinkProcedure:
			linkerServiceDeleteExplicitLinkHandler.ServeHTTP(w, r)
		case LinkerServiceLinkProcedure:
			linkerServiceLinkHandler.ServeHTTP(w, r)
		case LinkerServiceLinkDetailProcedure:
			linkerServiceLinkDetailHandler.ServeHTTP(w, r)
		case LinkerServiceGetKnownSetsProcedure:
			linkerServiceGetKnownSetsHandler.ServeHTTP(w, r)
		case LinkerServiceGetKnownKeysProcedure:
			linkerServiceGetKnownKeysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLinkerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLinkerServiceHandler struct{}

func (UnimplementedLinkerServiceHandler) GetExplicitLinks(context.Context, *connect.Request[v1.GetExplicitLinksRequest]) (*connect.Response[v1.GetExplicitLinksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.GetExplicitLinks is not implemented"))
}

func (UnimplementedLinkerServiceHandler) AddExplicitLink(context.Context, *connect.Request[v1.AddExplicitLinkRequest]) (*connect.Response[v1.AddExplicitLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.AddExplicitLink is not implemented"))
}

func (UnimplementedLinkerServiceHandler) DeleteExplicitLink(context.Context, *connect.Request[v1.DeleteExplicitLinkRequest]) (*connect.Response[v1.DeleteExplicitLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.DeleteExplicitLink is not implemented"))
}

func (UnimplementedLinkerServiceHandler) Link(context.Context, *connect.Request[v1.LinkRequest]) (*connect.Response[v1.LinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.Link is not implemented"))
}

func (UnimplementedLinkerServiceHandler) LinkDetail(context.Context, *connect.Request[v1.LinkDetailRequest]) (*connect.Response[v1.LinkDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.LinkDetail is not implemented"))
}

func (UnimplementedLinkerServiceHandler) GetKnownSets(context.Context, *connect.Request[v1.GetKnownSetsRequest]) (*connect.Response[v1.GetKnownSetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.GetKnownSets is not implemented"))
}

func (UnimplementedLinkerServiceHandler) GetKnownKeys(context.Context, *connect.Request[v1.GetKnownKeysRequest]) (*connect.Response[v1.GetKnownKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vcassist.services.linker.v1.LinkerService.GetKnownKeys is not implemented"))
}
